"""Data models for JARVIS AI Universal PC Problem Solver & Diagnostic Engine."""
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field
from datetime import datetime


class ProblemCategory(str, Enum):
    """Categorization of common PC hardware, OS, and software problems."""
    BLUETOOTH = "bluetooth"
    WIFI_NETWORK = "wifi_network"
    INTERNET = "internet"
    AUDIO = "audio"
    USB_INPUT = "usb_input"
    DISPLAY = "display"
    PERFORMANCE_HANG = "performance_hang"
    SLOW_SYSTEM = "slow_system"
    STORAGE = "storage"
    WINDOWS_UPDATE = "windows_update"
    SYSTEM_FILES = "system_files"
    APPLICATION = "application"
    DEV_ENVIRONMENT = "dev_environment"
    GENERIC_ERROR = "generic_error"
    SYSTEM_HEALTH = "system_health"


class DiagnosticStatus(str, Enum):
    """Status of an individual diagnostic check."""
    HEALTHY = "healthy"
    WARNING = "warning"
    PROBLEM_DETECTED = "problem_detected"
    UNAVAILABLE = "unavailable"
    UNKNOWN = "unknown"


class RiskLevel(str, Enum):
    """Safety and risk classification for repair actions."""
    LOW = "low"            # Read-only checks, service restarts, DNS flush, cache scans
    MEDIUM = "medium"      # Adapter resets, startup task tweaks, temporary file cleanups
    HIGH = "high"          # Driver removals, network stack reset, service disabling
    CRITICAL = "critical"  # Registry edits, system-wide repairs, large-scale cleanups


class DiagnosticItem(BaseModel):
    """An individual diagnostic metric or observation."""
    name: str = Field(..., description="Name of the component or metric.")
    status: DiagnosticStatus = Field(default=DiagnosticStatus.HEALTHY)
    value: Any = Field(None, description="Current value or status text.")
    details: Optional[str] = Field(None, description="Detailed diagnostic description.")
    error_code: Optional[str] = Field(None, description="Windows error code or device code if any.")


class DiagnosticReport(BaseModel):
    """Comprehensive diagnostic report generated by a diagnostic engine."""
    category: ProblemCategory
    timestamp: datetime = Field(default_factory=datetime.now)
    overall_status: DiagnosticStatus = DiagnosticStatus.HEALTHY
    summary: str = Field(..., description="Human-readable overview of diagnostic findings.")
    items: List[DiagnosticItem] = Field(default_factory=list)
    raw_evidence: Dict[str, Any] = Field(default_factory=dict, description="Structured raw data collected.")
    suggested_focus: Optional[str] = None


class RootCauseHypothesis(BaseModel):
    """A ranked hypothesis explaining the root cause of a detected issue."""
    rank: int = Field(1, description="Priority rank (1 being highest confidence).")
    title: str = Field(..., description="Short title of the root cause.")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score between 0.0 and 1.0.")
    explanation: str = Field(..., description="Detailed explanation linking evidence to the cause.")
    evidence_keys: List[str] = Field(default_factory=list, description="Keys of evidence supporting this hypothesis.")
    recommended_repair_type: str = Field(..., description="Identifier for the recommended repair.")


class RootCauseAnalysis(BaseModel):
    """Structured root cause analysis output."""
    category: ProblemCategory
    timestamp: datetime = Field(default_factory=datetime.now)
    primary_cause: Optional[RootCauseHypothesis] = None
    secondary_hypotheses: List[RootCauseHypothesis] = Field(default_factory=list)
    summary: str = Field(..., description="Concise human-like root cause summary.")
    requires_gemini_reasoning: bool = False


class RepairStep(BaseModel):
    """A single atomic repair action in a repair plan."""
    step_id: int
    name: str
    description: str
    risk_level: RiskLevel = RiskLevel.LOW
    requires_admin: bool = False
    requires_restart: bool = False
    action_type: str = Field(..., description="Type of repair action (e.g., restart_service, flush_dns).")
    parameters: Dict[str, Any] = Field(default_factory=dict)
    rollback_parameters: Optional[Dict[str, Any]] = None


class RepairPlan(BaseModel):
    """A safe, multi-step repair plan generated for an identified problem."""
    plan_id: str
    category: ProblemCategory
    created_at: datetime = Field(default_factory=datetime.now)
    title: str
    summary: str
    risk_level: RiskLevel = RiskLevel.LOW
    requires_confirmation: bool = False
    requires_restart: bool = False
    requires_admin: bool = False
    steps: List[RepairStep] = Field(default_factory=list)
    preview_data: Optional[Dict[str, Any]] = None
    rollback_available: bool = True


class VerificationResult(BaseModel):
    """Strict BEFORE vs AFTER verification outcome."""
    verified: bool = Field(..., description="True if and only if the problem condition has cleared.")
    timestamp: datetime = Field(default_factory=datetime.now)
    category: ProblemCategory
    before_state: Dict[str, Any] = Field(default_factory=dict)
    after_state: Dict[str, Any] = Field(default_factory=dict)
    message: str
    remaining_issues: List[str] = Field(default_factory=list)


class SnapshotData(BaseModel):
    """Logical snapshot of system state before a repair for rollback purposes."""
    snapshot_id: str
    created_at: datetime = Field(default_factory=datetime.now)
    category: ProblemCategory
    service_states: Dict[str, str] = Field(default_factory=dict)
    adapter_states: Dict[str, bool] = Field(default_factory=dict)
    config_state: Dict[str, Any] = Field(default_factory=dict)
    description: str = ""


class RepairHistoryEntry(BaseModel):
    """Persistent audit log entry for troubleshooting and repairs."""
    entry_id: str
    timestamp: datetime = Field(default_factory=datetime.now)
    problem_text: str
    category: ProblemCategory
    diagnosis_summary: str
    root_cause_title: Optional[str] = None
    repair_summary: Optional[str] = None
    verification_passed: bool = False
    rollback_applied: bool = False
